spring:
  application:
    name: linkio
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}